<?php

return [	

	'companies' => [
		[
			'url' => 'global',
			'name' => 'Supreme Global',
			'image' => 'supreme-global.png',
		],
		[
			'url' => 'supreme-tea',
			'name' => 'Supreme Tea Limited',
			'image' => 'supreme-tea.png',
		],
		[
			'url' => 'auto-bricks',
			'name' => 'A&A Auto Bricks Industries Ltd',
			'image' => 'auto-bricks.png',
		],
		[
			'url' => 'dar-kafaa',
			'name' => 'Dar Kafaa Al-Alia',
			'image' => 'dar-kafaa.png',
		],
		[
			'url' => 'supreme-agro',
			'name' => 'Supreme Agro',
			'image' => 'supreme-agro.png',
		],
		[
			'url' => 'north-point',
			'name' => 'North Point Medical College & Hospital Ltd',
			'image' => 'north-point.png',
		],
		/*
		[
			'url' => 'north-palace',
			'name' => 'North Palace Hotel & Resort Ltd',
			'image' => 'north-palace.png',
		],
		*/
		[
			'url' => 'garden-inn',
			'name' => 'Garden Inn Resort & Amusement',
			'image' => 'garden-inn.png',
		],
		[
			'url' => 'alif-co',
			'name' => 'ALIF & Co.',
			'image' => 'alif-co.png',
		],
	],

	'clients' => [
		'Cod BD Limited',
		'Ventura Leatherware Manufacturing BD Limited',
		'Section Seven International Limited',
		'Ahmed Wood and Board',
		'Win champion BD Limited',
		'Equ Jute Process',
		'Shamoli Cement Sheet Mills Ltd',
		'Classical Handmade Products BD Kirtaniapara',
		'Center Zakat Management',
		'Millennium Gold Limited',
		'Atamul Millennium Gold Supplier',
		'Ever green products factory BD Limited',
		'Margin Bangladesh Limited',
		'Sonic Bangladesh Limited',
		'EQE International Limited',
		'Rangpur group Private ltd',
		'Karupannya Rangpur Ltd',
		'Ishpahani ltd',
		'BRAC NGO',
		'Buro Bangladesh',
		'Nourish',
		'Paragon',
		'Bombay Agro',
		'Opsonin pharma',
		'Amena baki foundation',
		'Safi uddin ahmed foundation',

		'Abdullah Bakery',
		'Abdur hotel',
		'Afzal Store (Sakoa bazar)',
		'Anis tea house (Panchagarh)',
		'Azharul Store',
		'BGB canteen, Panchagarh',
		'Bhutto tea stall',
		'Humayon Store',
		'Ma baba\'r doa store',
		'Khaza mia hotel',
		'M/S bhai bhai store',
		'Mizan store (Jagdol)',
		'Montu bhai',
		'Muktadir Bhai',
		'Munshir hotel',
		'Rezaul store',
		'Zakir Store',
		'Adid confectionary',
		'Koli sweet',

		'ARAMCO',
		'Saudi Electricity Company (SEC)',
		'Etihad Etisalat (Mobily)',
		'Integrated Telecom Company (Salam Telecom)',
		'King Salman Park, Riyadh',
		'Al Yamama',
		'Middle Sea Telecom Company',
		'SAS Systems Engineering',
		'SANS International Company',
		'Technical Links Services',

		'North Point Medical College & Hospital',
		'North Palace Hotel & Resort',
		'Supreme Tea Limited',
		'Garden Inn Resort',
		'Bangladesh Water Development Board',
		'Department of Public Health Engineering',
		'Education Engineering Department',
		'Health Engineering Department',
		'PetroBangla',
		'Dhaka Electric Supply Company',
		'Northern Electric Supply Company',
		'Bangladesh Rural Electrification Board',
		'Bangladesh Telecommunication Company Ltd (BTCL)',
	],
];